version: "3.3"
services:
  database:
    image: 'postgres:13.0-alpine'
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
  app:
    image: 'hub.docker.com/msarniak/msarniak-shop:1.0'
    ports:
      - "8080:8080"
volumes:
  database-data:
